"""
Django settings for glasshouse_frontend project.

Generated by 'django-admin startproject' using Django 6.0.7, then hand-
edited for deployment: SECRET_KEY / DEBUG / ALLOWED_HOSTS now read from
environment variables (safe local defaults if unset), WhiteNoise serves
static files directly from the app process rather than needing a
separate static-file bucket, and cookies are hardened for a public
deployment. None of this affects local dev -- the defaults below are
exactly what `runserver` already used.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In deployment this comes from a Lambda environment variable, set by
# Terraform from a generated random_password resource -- see
# infra/README.md. The fallback below is the same one django-admin
# generated originally; it's fine for local dev, never for a real
# deployment, which is exactly why DJANGO_SECRET_KEY overrides it.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django-insecure-(kp90t)!p7z&w=r@v4*of%cl)u9e!pucii@y=7j7_=gd0hkn59"
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (safe) -- set DJANGO_DEBUG=true locally if you want
# Django's debug pages. Deliberately NOT defaulting to True, so a
# deployment that forgets to set this explicitly fails safe.
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h]

CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'pricing',
]

# Not using DRF's browsable-API session auth for this project (no user
# accounts, nothing to authenticate) -- keeping every endpoint open and
# stateless. See REST_FRAMEWORK below.
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must sit directly after SecurityMiddleware and before
    # everything else -- serves static files (just style.css, currently)
    # straight from the app process. Avoids standing up a second S3
    # bucket + CloudFront behavior just for one small stylesheet.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'glasshouse_frontend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'glasshouse_frontend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # `collectstatic` target -- run at
                                          # container build time, not here.

# STORAGES (not the older STATICFILES_STORAGE, deprecated since Django
# 4.2). Deliberately the *non*-manifest compressed variant: the
# manifest variant needs `collectstatic` to have already run to build a
# name->hashed-name lookup, which breaks local `runserver` and every
# test that renders a template with {% static %} -- neither runs
# collectstatic. This still gets WhiteNoise's gzip/brotli compression
# with zero setup; the only real difference in production is losing
# hash-based cache-busted filenames, an acceptable trade for a project
# with one small stylesheet that rarely changes.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Cookie hardening for a public deployment. Harmless locally over plain
# HTTP -- these only take effect when DEBUG is False, which local dev
# never is unless you've explicitly set DJANGO_DEBUG=true.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
